"""Phase 6A.2 evidence graph enumerations."""

from enum import StrEnum


class GraphNodeType(StrEnum):
    PIPELINE_RUN = "PIPELINE_RUN"
    WORKFLOW = "WORKFLOW"
    JOB = "JOB"
    STEP = "STEP"
    COMMAND = "COMMAND"
    LOG_EVENT = "LOG_EVENT"
    ERROR_EVENT = "ERROR_EVENT"
    WARNING_EVENT = "WARNING_EVENT"
    COMMIT = "COMMIT"
    CHANGED_FILE = "CHANGED_FILE"
    ENVIRONMENT_VARIABLE = "ENVIRONMENT_VARIABLE"
    SECRET_REFERENCE = "SECRET_REFERENCE"
    TERRAFORM_MODULE = "TERRAFORM_MODULE"
    TERRAFORM_RESOURCE = "TERRAFORM_RESOURCE"
    TERRAFORM_VARIABLE = "TERRAFORM_VARIABLE"
    TERRAFORM_OUTPUT = "TERRAFORM_OUTPUT"
    TERRAFORM_PROVIDER = "TERRAFORM_PROVIDER"
    TERRAFORM_DATA_SOURCE = "TERRAFORM_DATA_SOURCE"
    TERRAFORM_PLAN_CHANGE = "TERRAFORM_PLAN_CHANGE"
    AWS_SERVICE = "AWS_SERVICE"
    AWS_RESOURCE = "AWS_RESOURCE"
    AWS_PRINCIPAL = "AWS_PRINCIPAL"
    IAM_ROLE = "IAM_ROLE"
    IAM_POLICY = "IAM_POLICY"
    POLICY_STATEMENT = "POLICY_STATEMENT"
    PERMISSION_ACTION = "PERMISSION_ACTION"
    SECURITY_FINDING = "SECURITY_FINDING"
    # Reserved — unused in 6A.2
    HYPOTHESIS = "HYPOTHESIS"
    REMEDIATION = "REMEDIATION"
    OTHER = "OTHER"


class GraphEdgeType(StrEnum):
    # Workflow structure
    CONTAINS = "CONTAINS"
    NEEDS = "NEEDS"
    EXECUTES = "EXECUTES"
    USES_ACTION = "USES_ACTION"
    REFERENCES = "REFERENCES"
    PRODUCES_OUTPUT = "PRODUCES_OUTPUT"
    CONSUMES_OUTPUT = "CONSUMES_OUTPUT"
    # Temporal
    OCCURRED_BEFORE = "OCCURRED_BEFORE"
    OCCURRED_AFTER = "OCCURRED_AFTER"
    FAILED_AT = "FAILED_AT"
    DOWNSTREAM_SYMPTOM_OF = "DOWNSTREAM_SYMPTOM_OF"
    RETRY_OF = "RETRY_OF"
    PARALLEL_WITH = "PARALLEL_WITH"
    # Repository
    MODIFIED_BY = "MODIFIED_BY"
    CHANGED_IN = "CHANGED_IN"
    PREVIOUS_SUCCESS_OF = "PREVIOUS_SUCCESS_OF"
    # Terraform
    DECLARES = "DECLARES"
    DEPENDS_ON = "DEPENDS_ON"
    REFERENCES_RESOURCE = "REFERENCES_RESOURCE"
    REFERENCES_VARIABLE = "REFERENCES_VARIABLE"
    REFERENCES_OUTPUT = "REFERENCES_OUTPUT"
    USES_PROVIDER = "USES_PROVIDER"
    PLANS_CHANGE_TO = "PLANS_CHANGE_TO"
    # AWS/IAM
    ASSUMES_ROLE = "ASSUMES_ROLE"
    TARGETS_RESOURCE = "TARGETS_RESOURCE"
    REQUIRES_PERMISSION = "REQUIRES_PERMISSION"
    ALLOWS = "ALLOWS"
    DENIES = "DENIES"
    APPLIES_TO_PRINCIPAL = "APPLIES_TO_PRINCIPAL"
    APPLIES_TO_RESOURCE = "APPLIES_TO_RESOURCE"
    OPERATES_IN_REGION = "OPERATES_IN_REGION"
    # Cross-artifact
    LOG_REFERS_TO_RESOURCE = "LOG_REFERS_TO_RESOURCE"
    STEP_REFERENCES_TERRAFORM = "STEP_REFERENCES_TERRAFORM"
    WORKFLOW_VALUE_FEEDS_TERRAFORM = "WORKFLOW_VALUE_FEEDS_TERRAFORM"
    TERRAFORM_OUTPUT_USED_BY_STEP = "TERRAFORM_OUTPUT_USED_BY_STEP"
    ERROR_ASSOCIATED_WITH_POLICY = "ERROR_ASSOCIATED_WITH_POLICY"
    CHANGE_AFFECTS_NODE = "CHANGE_AFFECTS_NODE"
    CANDIDATE_CAUSE_OF = "CANDIDATE_CAUSE_OF"


class GraphDerivationType(StrEnum):
    PARSER_DETERMINISTIC = "PARSER_DETERMINISTIC"
    WORKFLOW_STRUCTURE = "WORKFLOW_STRUCTURE"
    TERRAFORM_REFERENCE = "TERRAFORM_REFERENCE"
    TEMPORAL_DETERMINISTIC = "TEMPORAL_DETERMINISTIC"
    TEMPORAL_HEURISTIC = "TEMPORAL_HEURISTIC"
    CROSS_ARTIFACT_RULE = "CROSS_ARTIFACT_RULE"
    LLM_INFERRED = "LLM_INFERRED"  # reserved; unused in 6A.2


class GraphConsistencyStatus(StrEnum):
    VALID = "VALID"
    VALID_WITH_WARNINGS = "VALID_WITH_WARNINGS"
    PARTIAL = "PARTIAL"
    INVALID = "INVALID"
    FAILED = "FAILED"
    DISABLED = "DISABLED"


class EvidenceGraphStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    DISABLED = "DISABLED"
    TRUNCATED = "TRUNCATED"
