"""Enums for Phase 6A.6 Part 1 counterfactual remediation (candidates only)."""

from __future__ import annotations

from enum import StrEnum


class CounterfactualRemediationRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_ELIGIBLE_HYPOTHESES = "NO_ELIGIBLE_HYPOTHESES"
    NO_SAFE_CANDIDATES = "NO_SAFE_CANDIDATES"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    DISABLED = "DISABLED"


class CounterfactualCandidateStatus(StrEnum):
    """Part 1 statuses — never VERIFIED / APPLIED / DEPLOYED / SUCCESSFUL."""

    DRAFT = "DRAFT"
    STRUCTURED = "STRUCTURED"
    INCOMPLETE = "INCOMPLETE"
    READY_FOR_GENERATION = "READY_FOR_GENERATION"
    READY_FOR_VERIFICATION = "READY_FOR_VERIFICATION"
    INVALID = "INVALID"
    REJECTED = "REJECTED"
    UNSAFE = "UNSAFE"
    DISABLED = "DISABLED"
    FAILED = "FAILED"


class RemediationArtifactType(StrEnum):
    GITHUB_WORKFLOW = "GITHUB_WORKFLOW"
    REUSABLE_WORKFLOW = "REUSABLE_WORKFLOW"
    TERRAFORM_CONFIGURATION = "TERRAFORM_CONFIGURATION"
    TERRAFORM_VARIABLES = "TERRAFORM_VARIABLES"
    TERRAFORM_POLICY = "TERRAFORM_POLICY"
    IAM_POLICY = "IAM_POLICY"
    RESOURCE_POLICY = "RESOURCE_POLICY"
    DOCKERFILE = "DOCKERFILE"
    DOCKER_COMPOSE = "DOCKER_COMPOSE"
    KUBERNETES_MANIFEST = "KUBERNETES_MANIFEST"
    DEPENDENCY_MANIFEST = "DEPENDENCY_MANIFEST"
    LOCK_FILE = "LOCK_FILE"
    APPLICATION_CONFIGURATION = "APPLICATION_CONFIGURATION"
    ENVIRONMENT_CONFIGURATION = "ENVIRONMENT_CONFIGURATION"
    SOURCE_CODE = "SOURCE_CODE"
    UNKNOWN = "UNKNOWN"


class CounterfactualChangeType(StrEnum):
    ADD = "ADD"
    REMOVE = "REMOVE"
    REPLACE = "REPLACE"
    UPDATE_REFERENCE = "UPDATE_REFERENCE"
    UPDATE_VALUE = "UPDATE_VALUE"
    UPDATE_PERMISSION = "UPDATE_PERMISSION"
    UPDATE_CONDITION = "UPDATE_CONDITION"
    UPDATE_DEPENDENCY = "UPDATE_DEPENDENCY"
    UPDATE_VERSION = "UPDATE_VERSION"
    UPDATE_REGION = "UPDATE_REGION"
    UPDATE_ROLE = "UPDATE_ROLE"
    UPDATE_RESOURCE_TARGET = "UPDATE_RESOURCE_TARGET"
    UPDATE_JOB_DEPENDENCY = "UPDATE_JOB_DEPENDENCY"
    UPDATE_WORKFLOW_EXPRESSION = "UPDATE_WORKFLOW_EXPRESSION"
    UPDATE_ENVIRONMENT_REFERENCE = "UPDATE_ENVIRONMENT_REFERENCE"
    NO_CHANGE_POSSIBLE = "NO_CHANGE_POSSIBLE"
    UNKNOWN = "UNKNOWN"


class RemediationVerificationStatus(StrEnum):
    """Reserved Part 1 values only — no PASSED/FAILED decisions."""

    NOT_RUN = "NOT_RUN"
    UNAVAILABLE = "UNAVAILABLE"
    PENDING = "PENDING"


class ConstraintSeverity(StrEnum):
    BLOCKING = "BLOCKING"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFORMATIONAL = "INFORMATIONAL"


class ConstraintSourceType(StrEnum):
    WORKFLOW = "WORKFLOW"
    TERRAFORM = "TERRAFORM"
    TERRAFORM_PLAN = "TERRAFORM_PLAN"
    AWS_ERROR = "AWS_ERROR"
    IAM_POLICY = "IAM_POLICY"
    RESOURCE_POLICY = "RESOURCE_POLICY"
    SECURITY_POLICY = "SECURITY_POLICY"
    EVIDENCE_GRAPH = "EVIDENCE_GRAPH"
    TEMPORAL = "TEMPORAL"
    REPOSITORY = "REPOSITORY"
    PROJECT_CONFIGURATION = "PROJECT_CONFIGURATION"
    USER_REQUIREMENT = "USER_REQUIREMENT"
    ORGANIZATION_POLICY = "ORGANIZATION_POLICY"
    SYSTEM_POLICY = "SYSTEM_POLICY"
    HISTORICAL_INCIDENT = "HISTORICAL_INCIDENT"
    OFFICIAL_DOCUMENTATION = "OFFICIAL_DOCUMENTATION"
    UNKNOWN = "UNKNOWN"


class ConstraintType(StrEnum):
    SYNTAX = "SYNTAX"
    SCHEMA = "SCHEMA"
    REFERENCE = "REFERENCE"
    DEPENDENCY = "DEPENDENCY"
    PERMISSION = "PERMISSION"
    LEAST_PRIVILEGE = "LEAST_PRIVILEGE"
    EXPLICIT_DENY = "EXPLICIT_DENY"
    REGION = "REGION"
    ACCOUNT = "ACCOUNT"
    ENVIRONMENT = "ENVIRONMENT"
    RESOURCE_SCOPE = "RESOURCE_SCOPE"
    SECURITY = "SECURITY"
    ENCRYPTION = "ENCRYPTION"
    PUBLIC_ACCESS = "PUBLIC_ACCESS"
    NETWORK = "NETWORK"
    VERSION = "VERSION"
    COMPATIBILITY = "COMPATIBILITY"
    IMMUTABILITY = "IMMUTABILITY"
    DELETION_PROTECTION = "DELETION_PROTECTION"
    REPLACEMENT_RISK = "REPLACEMENT_RISK"
    OPERATIONAL = "OPERATIONAL"
    ROLLBACK = "ROLLBACK"
    COST = "COST"
    ORGANIZATION_POLICY = "ORGANIZATION_POLICY"
    USER_INTENT = "USER_INTENT"
    EVIDENCE_LIMITATION = "EVIDENCE_LIMITATION"


class ConstraintSatisfactionStatus(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    SATISFIED_BY_STRUCTURE = "SATISFIED_BY_STRUCTURE"
    UNSATISFIED_BY_STRUCTURE = "UNSATISFIED_BY_STRUCTURE"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ConstraintExtractionStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_CONSTRAINTS = "NO_CONSTRAINTS"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"
    DISABLED = "DISABLED"


class ConstraintSetCompleteness(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class ExpectedFailureConditionStatus(StrEnum):
    EXPECTED_REMOVED = "EXPECTED_REMOVED"
    EXPECTED_REDUCED = "EXPECTED_REDUCED"
    EXPECTED_UNCHANGED = "EXPECTED_UNCHANGED"
    UNKNOWN = "UNKNOWN"


class PreconditionStatus(StrEnum):
    SATISFIED = "SATISFIED"
    NOT_SATISFIED = "NOT_SATISFIED"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class MinimalChangePlanStatus(StrEnum):
    READY_FOR_GENERATION = "READY_FOR_GENERATION"
    INCOMPLETE = "INCOMPLETE"
    BLOCKED_BY_CONSTRAINTS = "BLOCKED_BY_CONSTRAINTS"
    NO_SAFE_CHANGE = "NO_SAFE_CHANGE"
    UNSUPPORTED_ARTIFACT = "UNSUPPORTED_ARTIFACT"
    FAILED = "FAILED"
    DISABLED = "DISABLED"


class HypothesisEligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    ELIGIBLE_WITH_WARNINGS = "ELIGIBLE_WITH_WARNINGS"
    INCOMPLETE = "INCOMPLETE"
    INELIGIBLE = "INELIGIBLE"
    BLOCKED = "BLOCKED"


class CandidateStructuralValidationStatus(StrEnum):
    VALID_STRUCTURE = "VALID_STRUCTURE"
    VALID_WITH_WARNINGS = "VALID_WITH_WARNINGS"
    INCOMPLETE = "INCOMPLETE"
    INVALID = "INVALID"
    UNSAFE = "UNSAFE"
    BLOCKED = "BLOCKED"


class RollbackType(StrEnum):
    RESTORE_ORIGINAL_FRAGMENT = "RESTORE_ORIGINAL_FRAGMENT"
    RESTORE_ORIGINAL_FILE = "RESTORE_ORIGINAL_FILE"
    REVERT_REFERENCE = "REVERT_REFERENCE"
    RESTORE_VERSION = "RESTORE_VERSION"
    MANUAL_REQUIRED = "MANUAL_REQUIRED"
    NOT_AVAILABLE = "NOT_AVAILABLE"


class RemediationRiskType(StrEnum):
    PERMISSION_EXPANSION = "PERMISSION_EXPANSION"
    WILDCARD_ACCESS = "WILDCARD_ACCESS"
    PUBLIC_EXPOSURE = "PUBLIC_EXPOSURE"
    ENCRYPTION_REMOVAL = "ENCRYPTION_REMOVAL"
    RESOURCE_REPLACEMENT = "RESOURCE_REPLACEMENT"
    RESOURCE_DELETION = "RESOURCE_DELETION"
    CROSS_ACCOUNT_CHANGE = "CROSS_ACCOUNT_CHANGE"
    REGION_CHANGE = "REGION_CHANGE"
    ENVIRONMENT_CHANGE = "ENVIRONMENT_CHANGE"
    MULTI_FILE_CHANGE = "MULTI_FILE_CHANGE"
    HIGH_BLAST_RADIUS = "HIGH_BLAST_RADIUS"
    ROLLBACK_UNCERTAINTY = "ROLLBACK_UNCERTAINTY"
    TEST_BYPASS = "TEST_BYPASS"
    POLICY_BYPASS = "POLICY_BYPASS"
    SECRET_EXPOSURE = "SECRET_EXPOSURE"
    DEPENDENCY_BREAKAGE = "DEPENDENCY_BREAKAGE"
    UNKNOWN_SIDE_EFFECT = "UNKNOWN_SIDE_EFFECT"


class VerifierType(StrEnum):
    """Reserved verifier types — not executed in Part 1."""

    WORKFLOW_YAML_PARSE = "WORKFLOW_YAML_PARSE"
    ACTIONLINT = "ACTIONLINT"
    TERRAFORM_FMT = "TERRAFORM_FMT"
    TERRAFORM_VALIDATE = "TERRAFORM_VALIDATE"
    TERRAFORM_PLAN = "TERRAFORM_PLAN"
    TERRAFORM_DEPENDENCY = "TERRAFORM_DEPENDENCY"
    IAM_POLICY_STRUCTURE = "IAM_POLICY_STRUCTURE"
    IAM_LEAST_PRIVILEGE = "IAM_LEAST_PRIVILEGE"
    CHECKOV = "CHECKOV"
    OPA = "OPA"
    SECURITY_REGRESSION = "SECURITY_REGRESSION"
    COUNTERFACTUAL_FAILURE_CONDITION = "COUNTERFACTUAL_FAILURE_CONDITION"
