"""Enums for Phase 6A.6 Part 2 remediation generation (candidates only)."""

from __future__ import annotations

from enum import StrEnum


class RemediationGeneratorType(StrEnum):
    RULE_TEMPLATE = "RULE_TEMPLATE"
    STRUCTURED_RULE = "STRUCTURED_RULE"
    LLM_STRUCTURED = "LLM_STRUCTURED"
    HISTORICAL_ADAPTATION = "HISTORICAL_ADAPTATION"
    PREVIOUS_SUCCESS_RESTORATION = "PREVIOUS_SUCCESS_RESTORATION"
    HYBRID = "HYBRID"


class RemediationGenerationStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_APPLICABLE_TEMPLATE = "NO_APPLICABLE_TEMPLATE"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    DISABLED = "DISABLED"


class CandidatePriorityStatus(StrEnum):
    PRIORITY_CANDIDATE = "PRIORITY_CANDIDATE"
    ALTERNATIVE_CANDIDATE = "ALTERNATIVE_CANDIDATE"
    HIGH_RISK_CANDIDATE = "HIGH_RISK_CANDIDATE"
    INCOMPLETE_CANDIDATE = "INCOMPLETE_CANDIDATE"
    REJECTED_CANDIDATE = "REJECTED_CANDIDATE"
    NO_SAFE_CANDIDATE = "NO_SAFE_CANDIDATE"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class BlastRadiusLevel(StrEnum):
    LOCAL = "LOCAL"
    LIMITED = "LIMITED"
    MODERATE = "MODERATE"
    BROAD = "BROAD"
    UNKNOWN = "UNKNOWN"


class ConstraintValidationStatus(StrEnum):
    STRUCTURALLY_COMPLIANT = "STRUCTURALLY_COMPLIANT"
    COMPLIANT_WITH_WARNINGS = "COMPLIANT_WITH_WARNINGS"
    INCOMPLETE = "INCOMPLETE"
    BLOCKED = "BLOCKED"
    UNSAFE = "UNSAFE"
    INVALID = "INVALID"


class PatchFormat(StrEnum):
    YAML_FRAGMENT = "YAML_FRAGMENT"
    JSON_FRAGMENT = "JSON_FRAGMENT"
    IAM_POLICY_JSON = "IAM_POLICY_JSON"
    HCL_FRAGMENT = "HCL_FRAGMENT"
    TEXT_FRAGMENT = "TEXT_FRAGMENT"
    DEPENDENCY_MANIFEST = "DEPENDENCY_MANIFEST"
    UNIFIED_DIFF = "UNIFIED_DIFF"
    UNSUPPORTED = "UNSUPPORTED"
