"""Phase 6A.2 temporal localisation enumerations."""

from enum import StrEnum


class TemporalEventType(StrEnum):
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    JOB_STARTED = "JOB_STARTED"
    STEP_STARTED = "STEP_STARTED"
    COMMAND_EXECUTED = "COMMAND_EXECUTED"
    WARNING = "WARNING"
    ERROR = "ERROR"
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TERRAFORM_DIAGNOSTIC = "TERRAFORM_DIAGNOSTIC"
    TEST_FAILURE = "TEST_FAILURE"
    DEPENDENCY_FAILURE = "DEPENDENCY_FAILURE"
    RESOURCE_FAILURE = "RESOURCE_FAILURE"
    TIMEOUT = "TIMEOUT"
    RETRY = "RETRY"
    CANCELLATION = "CANCELLATION"
    JOB_FAILED = "JOB_FAILED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    INFO = "INFO"


class TemporalLinkType(StrEnum):
    OCCURRED_BEFORE = "OCCURRED_BEFORE"
    OCCURRED_AFTER = "OCCURRED_AFTER"
    SAME_STEP = "SAME_STEP"
    SAME_JOB = "SAME_JOB"
    TRIGGERED_RETRY = "TRIGGERED_RETRY"
    PRECEDED_FAILURE = "PRECEDED_FAILURE"
    DOWNSTREAM_SYMPTOM_OF = "DOWNSTREAM_SYMPTOM_OF"
    CANDIDATE_CAUSE_OF = "CANDIDATE_CAUSE_OF"
    PARALLEL_WITH = "PARALLEL_WITH"
    DEPENDS_ON_JOB = "DEPENDS_ON_JOB"


class TemporalOrderingMethod(StrEnum):
    TIMESTAMP = "TIMESTAMP"
    PARSER_SEQUENCE = "PARSER_SEQUENCE"
    MIXED = "MIXED"
    PARTIAL = "PARTIAL"


class TimestampQuality(StrEnum):
    PRECISE = "PRECISE"
    COARSE = "COARSE"
    ABSENT = "ABSENT"
    CONFLICTING = "CONFLICTING"


class TemporalLocalisationStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INCONCLUSIVE = "INCONCLUSIVE"
    FAILED = "FAILED"
    DISABLED = "DISABLED"


class TemporalLinkDerivation(StrEnum):
    TEMPORAL_DETERMINISTIC = "TEMPORAL_DETERMINISTIC"
    WORKFLOW_STRUCTURE = "WORKFLOW_STRUCTURE"
    TEMPORAL_HEURISTIC = "TEMPORAL_HEURISTIC"
