"""Re-export Phase 6A.6 Part 1 version identifiers from the domain package."""

from __future__ import annotations

from app.domain.counterfactual_remediation.versions import (
    CONSTRAINT_EXTRACTOR_VERSION,
    COUNTERFACTUAL_CONTEXT_VERSION,
    COUNTERFACTUAL_REMEDIATION_SNAPSHOT_VERSION,
    COUNTERFACTUAL_STATE_VERSION,
    MINIMAL_CHANGE_PLANNER_VERSION,
    REMEDIATION_CANDIDATE_VALIDATOR_VERSION,
    REMEDIATION_CONSTRAINTS_VERSION,
    REMEDIATION_CURRENT_STATE_VERSION,
    REMEDIATION_TEMPLATES_VERSION,
)

__all__ = [
    "CONSTRAINT_EXTRACTOR_VERSION",
    "COUNTERFACTUAL_CONTEXT_VERSION",
    "COUNTERFACTUAL_REMEDIATION_SNAPSHOT_VERSION",
    "COUNTERFACTUAL_STATE_VERSION",
    "MINIMAL_CHANGE_PLANNER_VERSION",
    "REMEDIATION_CANDIDATE_VALIDATOR_VERSION",
    "REMEDIATION_CONSTRAINTS_VERSION",
    "REMEDIATION_CURRENT_STATE_VERSION",
    "REMEDIATION_TEMPLATES_VERSION",
]
