"""Thirty-four Phase 4B end-to-end regression scenarios (secret-free fixtures)."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Scenario:
    id: str
    technology: str
    expected_failure_state: bool
    expected_primary_category: str
    expected_technology_signal: str | None
    min_evidence_hint: int
    expect_recommendations: bool
    llm_acceptable_fallback: bool
    log: str


SCENARIOS: tuple[Scenario, ...] = (
    Scenario(
        "e2e-aws-01",
        "aws",
        True,
        "aws_permission_failure",
        "AWS",
        1,
        True,
        True,
        "ERROR AccessDenied User is not authorized to perform: sts:AssumeRole",
    ),
    Scenario(
        "e2e-aws-02",
        "aws",
        True,
        "aws_permission_failure",
        "AWS",
        1,
        True,
        True,
        "aws sts assume-role\nExpiredToken: The security token included in the request is expired",
    ),
    Scenario(
        "e2e-aws-03",
        "aws",
        True,
        "aws_permission_failure",
        "AWS",
        1,
        True,
        True,
        "An error occurred (UnauthorizedOperation) when calling the Amazon EC2 API:\n"
        "You are not authorized to perform this operation\naws ec2 describe-instances",
    ),
    Scenario(
        "e2e-tf-01",
        "terraform",
        True,
        "terraform_failure",
        "Terraform",
        1,
        True,
        True,
        "Error: Reference to undeclared resource\n  on main.tf line 12\nterraform validate failed",
    ),
    Scenario(
        "e2e-tf-02",
        "terraform",
        True,
        "terraform_failure",
        "Terraform",
        1,
        True,
        True,
        "Error acquiring the state lock\nterraform apply\nstate locked by another process",
    ),
    Scenario(
        "e2e-tf-03",
        "terraform",
        True,
        "terraform_failure",
        "Terraform",
        1,
        True,
        True,
        "terraform init\nError: Invalid provider configuration\n"
        "provider configuration for aws failed\n.tf provider block",
    ),
    Scenario(
        "e2e-tf-04",
        "terraform",
        False,
        "unknown_failure",
        "Terraform",
        0,
        False,
        True,
        "terraform init\nTerraform has been successfully initialized!\n"
        "terraform plan\nPlan: 1 to add, 0 to change, 0 to destroy.\nJob succeeded",
    ),
    Scenario(
        "e2e-docker-01",
        "docker",
        True,
        "docker_failure",
        "Docker",
        1,
        True,
        True,
        "failed to solve: failed to compute cache key: failed to read dockerfile\n"
        "COPY failed: file not found in build context",
    ),
    Scenario(
        "e2e-docker-02",
        "docker",
        True,
        "docker_failure",
        "Docker",
        1,
        True,
        True,
        "error building image: docker build failed: unable to prepare context",
    ),
    Scenario(
        "e2e-docker-03",
        "docker",
        True,
        "docker_failure",
        "Docker",
        1,
        True,
        True,
        "docker pull myorg/app:latest\npull access denied for myorg/app, repository does not exist",
    ),
    Scenario(
        "e2e-gha-01",
        "github_actions",
        True,
        "ci_runner_failure",
        "GitHub Actions",
        1,
        True,
        True,
        "The self-hosted runner is offline\n"
        "Waiting for a self-hosted runner\nruns-on: [self-hosted]",
    ),
    Scenario(
        "e2e-gha-02",
        "github_actions",
        True,
        "ci_runner_failure",
        "GitHub Actions",
        1,
        True,
        True,
        "GITHUB_ACTIONS=true\nNo runner matching the requested labels was found\n"
        "Job is waiting for a runner\nruns-on: ubuntu-latest",
    ),
    Scenario(
        "e2e-gha-03",
        "github_actions",
        True,
        "build_failure",
        "GitHub Actions",
        1,
        True,
        True,
        "GITHUB_ACTIONS=true\n##[error]Process completed with exit code 1\n"
        "compilation failed\nBUILD FAILURE",
    ),
    Scenario(
        "e2e-gha-04",
        "github_actions",
        False,
        "unknown_failure",
        "GitHub Actions",
        0,
        False,
        True,
        "GITHUB_ACTIONS=true\nAll checks passed\nJob succeeded\nexit code 0",
    ),
    Scenario(
        "e2e-k8s-01",
        "kubernetes",
        True,
        "deployment_failure",
        "Kubernetes",
        1,
        True,
        True,
        "Warning Failed ImagePullBackOff\nkubectl describe pod\ndeployment failed",
    ),
    Scenario(
        "e2e-k8s-02",
        "kubernetes",
        True,
        "deployment_failure",
        "Kubernetes",
        1,
        True,
        True,
        "kubectl get pods\nCrashLoopBackOff Back-off restarting failed pod\n"
        "kubernetes deployment failed",
    ),
    Scenario(
        "e2e-k8s-03",
        "kubernetes",
        True,
        "deployment_failure",
        "Kubernetes",
        1,
        True,
        True,
        "kubectl describe pod\n0/3 nodes are available: insufficient cpu\n"
        "kubernetes deployment failed scheduling",
    ),
    Scenario(
        "e2e-k8s-04",
        "kubernetes",
        True,
        "deployment_failure",
        "Kubernetes",
        1,
        True,
        True,
        "kubectl rollout status\nError: timed out waiting for the condition\n"
        "kubernetes deploy failed\nHelm ERROR",
    ),
    Scenario(
        "e2e-npm-01",
        "node",
        True,
        "dependency_failure",
        "npm",
        1,
        True,
        True,
        "npm ERR! ERESOLVE unable to resolve dependency tree\nCould not resolve dependency",
    ),
    Scenario(
        "e2e-npm-02",
        "node",
        True,
        "dependency_failure",
        "npm",
        1,
        True,
        True,
        "npm ERR! 404 Not Found - GET https://registry.npmjs.org/missing-pkg",
    ),
    Scenario(
        "e2e-npm-03",
        "node",
        True,
        "dependency_failure",
        "Node.js",
        1,
        True,
        True,
        'error engine Unsupported engine\nnpm ERR! notsup Required: {"node":">=20"}',
    ),
    Scenario(
        "e2e-java-01",
        "java",
        True,
        "build_failure",
        "Maven",
        1,
        True,
        True,
        "Could not resolve dependencies for project\nmvn dependency:resolve FAILURE",
    ),
    Scenario(
        "e2e-java-02",
        "java",
        True,
        "build_failure",
        "Gradle",
        1,
        True,
        True,
        "Gradle build failed\nCould not resolve all files for configuration",
    ),
    Scenario(
        "e2e-java-03",
        "java",
        True,
        "build_failure",
        "Java",
        1,
        True,
        True,
        "Exception in thread main\ncompilation failed\nerror: cannot find symbol\n"
        "java compile FAILURE",
    ),
    Scenario(
        "e2e-py-01",
        "python",
        True,
        "dependency_failure",
        "Python",
        1,
        True,
        True,
        "Traceback (most recent call last):\nModuleNotFoundError: No module named 'requests'\n"
        "python -m pip install failed",
    ),
    Scenario(
        "e2e-py-02",
        "python",
        True,
        "dependency_failure",
        "pip",
        1,
        True,
        True,
        "pip install foo==9.9.9\nERROR: Could not find a version that satisfies the requirement "
        "foo==9.9.9\nResolutionImpossible",
    ),
    Scenario(
        "e2e-py-03",
        "python",
        True,
        "dependency_failure",
        "pip",
        1,
        True,
        True,
        "ERROR: Failed building wheel for cryptography\npip install.*failed",
    ),
    Scenario(
        "e2e-net-01",
        "network",
        True,
        "network_failure",
        None,
        1,
        True,
        True,
        "Could not resolve host: registry.npmjs.org\nName or service not known",
    ),
    Scenario(
        "e2e-sec-01",
        "tls",
        True,
        "security_misconfiguration",
        None,
        1,
        True,
        True,
        "certificate verify failed: certificate has expired\nTLS handshake error",
    ),
    Scenario(
        "e2e-disk-01",
        "platform",
        True,
        "unknown_failure",
        None,
        0,
        True,
        True,
        "OSError: [Errno 28] No space left on device\nfailed writing artifact",
    ),
    Scenario(
        "e2e-mem-01",
        "platform",
        True,
        "unknown_failure",
        None,
        0,
        True,
        True,
        "java.lang.OutOfMemoryError: Java heap space\nprocess killed",
    ),
    Scenario(
        "e2e-port-01",
        "platform",
        True,
        "unknown_failure",
        None,
        0,
        True,
        True,
        "Error: listen EADDRINUSE: address already in use :::8080\nfailed to bind",
    ),
    Scenario(
        "e2e-unk-01",
        "unknown",
        True,
        "unknown_failure",
        None,
        0,
        True,
        True,
        "something went wrong in the overnight batch job\nsee operator notes",
    ),
    Scenario(
        "e2e-ok-01",
        "generic",
        False,
        "unknown_failure",
        None,
        0,
        False,
        True,
        "Pipeline completed successfully\nAll stages passed\nexit code 0\nJob succeeded",
    ),
)


assert len(SCENARIOS) >= 30
