"""Enums for Phase 6A.5 hypothesis-directed retrieval."""

from __future__ import annotations

from enum import StrEnum


class HypothesisRetrievalRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_EVIDENCE = "NO_EVIDENCE"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    DISABLED = "DISABLED"


class HypothesisRetrievalSessionStatus(StrEnum):
    PENDING = "PENDING"
    PLANNED = "PLANNED"
    RETRIEVING = "RETRIEVING"
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_EVIDENCE = "NO_EVIDENCE"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    SKIPPED = "SKIPPED"


class HypothesisRetrievalSourceType(StrEnum):
    ARTIFACT = "ARTIFACT"
    GRAPH = "GRAPH"
    TEMPORAL = "TEMPORAL"
    STATIC_KNOWLEDGE = "STATIC_KNOWLEDGE"
    VECTOR_KNOWLEDGE = "VECTOR_KNOWLEDGE"
    LEXICAL_KNOWLEDGE = "LEXICAL_KNOWLEDGE"
    HISTORICAL_INCIDENT = "HISTORICAL_INCIDENT"
    DOCUMENTATION = "DOCUMENTATION"
    CLASSIFICATION = "CLASSIFICATION"
    REPOSITORY_CHANGE = "REPOSITORY_CHANGE"


class RetrievalQueryType(StrEnum):
    CAUSAL_CLAIM = "CAUSAL_CLAIM"
    ERROR_SIGNATURE = "ERROR_SIGNATURE"
    ARTIFACT_REFERENCE = "ARTIFACT_REFERENCE"
    RESOURCE_REFERENCE = "RESOURCE_REFERENCE"
    PERMISSION_ACTION = "PERMISSION_ACTION"
    FAILURE_CATEGORY = "FAILURE_CATEGORY"
    EXPECTED_OBSERVATION = "EXPECTED_OBSERVATION"
    FALSIFYING_OBSERVATION = "FALSIFYING_OBSERVATION"
    HISTORICAL_SIMILARITY = "HISTORICAL_SIMILARITY"
    GRAPH_NEIGHBORHOOD = "GRAPH_NEIGHBORHOOD"
    CUSTOM_RULE = "CUSTOM_RULE"


class RetrievalItemRelation(StrEnum):
    """Candidate relations only — not proven support/contradiction (Part 2+)."""

    SUPPORT_CANDIDATE = "SUPPORT_CANDIDATE"
    CONTRADICTION_CANDIDATE = "CONTRADICTION_CANDIDATE"
    CONTEXT = "CONTEXT"
    UNKNOWN = "UNKNOWN"


class RetrievalExecutionMode(StrEnum):
    RULE_ONLY = "RULE_ONLY"
    SINGLE_QUERY = "SINGLE_QUERY"
    MULTI_QUERY = "MULTI_QUERY"
    HYBRID = "HYBRID"
    DISABLED = "DISABLED"


class RetrievalFailureType(StrEnum):
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    TIMEOUT = "TIMEOUT"
    RATE_LIMIT = "RATE_LIMIT"
    EMBEDDING_FAILURE = "EMBEDDING_FAILURE"
    VECTOR_STORE_FAILURE = "VECTOR_STORE_FAILURE"
    PARSE_FAILURE = "PARSE_FAILURE"
    INVALID_QUERY = "INVALID_QUERY"
    ORGANIZATION_SCOPE_FAILURE = "ORGANIZATION_SCOPE_FAILURE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
