"""Enums for Phase 6A.5 hypothesis-directed retrieval."""

from __future__ import annotations

from enum import StrEnum


class HypothesisRetrievalRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_EVIDENCE = "NO_EVIDENCE"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    DISABLED = "DISABLED"


class HypothesisRetrievalSessionStatus(StrEnum):
    PENDING = "PENDING"
    PLANNED = "PLANNED"
    RETRIEVING = "RETRIEVING"
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_EVIDENCE = "NO_EVIDENCE"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    SKIPPED = "SKIPPED"


class HypothesisRetrievalSourceType(StrEnum):
    ARTIFACT = "ARTIFACT"
    GRAPH = "GRAPH"
    TEMPORAL = "TEMPORAL"
    STATIC_KNOWLEDGE = "STATIC_KNOWLEDGE"
    VECTOR_KNOWLEDGE = "VECTOR_KNOWLEDGE"
    LEXICAL_KNOWLEDGE = "LEXICAL_KNOWLEDGE"
    HISTORICAL_INCIDENT = "HISTORICAL_INCIDENT"
    DOCUMENTATION = "DOCUMENTATION"
    CLASSIFICATION = "CLASSIFICATION"
    REPOSITORY_CHANGE = "REPOSITORY_CHANGE"


class RetrievalQueryType(StrEnum):
    CAUSAL_CLAIM = "CAUSAL_CLAIM"
    ERROR_SIGNATURE = "ERROR_SIGNATURE"
    ARTIFACT_REFERENCE = "ARTIFACT_REFERENCE"
    RESOURCE_REFERENCE = "RESOURCE_REFERENCE"
    PERMISSION_ACTION = "PERMISSION_ACTION"
    FAILURE_CATEGORY = "FAILURE_CATEGORY"
    EXPECTED_OBSERVATION = "EXPECTED_OBSERVATION"
    FALSIFYING_OBSERVATION = "FALSIFYING_OBSERVATION"
    HISTORICAL_SIMILARITY = "HISTORICAL_SIMILARITY"
    GRAPH_NEIGHBORHOOD = "GRAPH_NEIGHBORHOOD"
    CUSTOM_RULE = "CUSTOM_RULE"


class RetrievalItemRelation(StrEnum):
    """Candidate relations only — not proven support/contradiction (Part 2+)."""

    SUPPORT_CANDIDATE = "SUPPORT_CANDIDATE"
    CONTRADICTION_CANDIDATE = "CONTRADICTION_CANDIDATE"
    CONTEXT = "CONTEXT"
    UNKNOWN = "UNKNOWN"


class RetrievalExecutionMode(StrEnum):
    RULE_ONLY = "RULE_ONLY"
    SINGLE_QUERY = "SINGLE_QUERY"
    MULTI_QUERY = "MULTI_QUERY"
    HYBRID = "HYBRID"
    DISABLED = "DISABLED"


class RetrievalFailureType(StrEnum):
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    TIMEOUT = "TIMEOUT"
    RATE_LIMIT = "RATE_LIMIT"
    EMBEDDING_FAILURE = "EMBEDDING_FAILURE"
    VECTOR_STORE_FAILURE = "VECTOR_STORE_FAILURE"
    PARSE_FAILURE = "PARSE_FAILURE"
    INVALID_QUERY = "INVALID_QUERY"
    ORGANIZATION_SCOPE_FAILURE = "ORGANIZATION_SCOPE_FAILURE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class QueryIntentType(StrEnum):
    CONFIRM_CAUSAL_CLAIM = "CONFIRM_CAUSAL_CLAIM"
    FIND_CONTRADICTION_CANDIDATE = "FIND_CONTRADICTION_CANDIDATE"
    RESOLVE_MISSING_EVIDENCE = "RESOLVE_MISSING_EVIDENCE"
    VERIFY_ARTIFACT_RELATIONSHIP = "VERIFY_ARTIFACT_RELATIONSHIP"
    FIND_HISTORICAL_ANALOGUE = "FIND_HISTORICAL_ANALOGUE"
    FIND_OFFICIAL_CONSTRAINT = "FIND_OFFICIAL_CONSTRAINT"
    FIND_POLICY_BEHAVIOR = "FIND_POLICY_BEHAVIOR"
    FIND_CONFIGURATION_REQUIREMENT = "FIND_CONFIGURATION_REQUIREMENT"
    FIND_PRIOR_SUCCESS_DIFFERENCE = "FIND_PRIOR_SUCCESS_DIFFERENCE"
    FIND_EXACT_FAILURE_SIGNATURE = "FIND_EXACT_FAILURE_SIGNATURE"
    FIND_RESOURCE_RELATIONSHIP = "FIND_RESOURCE_RELATIONSHIP"
    FIND_PERMISSION_RELATIONSHIP = "FIND_PERMISSION_RELATIONSHIP"
    EXPLORE_NOVEL_SIGNATURE = "EXPLORE_NOVEL_SIGNATURE"


class RetrievalValidationStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    ACCEPTED_WITH_WARNINGS = "ACCEPTED_WITH_WARNINGS"
    REJECTED_INVALID_PROVENANCE = "REJECTED_INVALID_PROVENANCE"
    REJECTED_SCOPE = "REJECTED_SCOPE"
    REJECTED_EMPTY = "REJECTED_EMPTY"
    REJECTED_SECRET_RISK = "REJECTED_SECRET_RISK"
    REJECTED_DUPLICATE = "REJECTED_DUPLICATE"
    REJECTED_IRRELEVANT = "REJECTED_IRRELEVANT"
    REJECTED_MALFORMED = "REJECTED_MALFORMED"
    REJECTED_ARCHIVED = "REJECTED_ARCHIVED"
    REJECTED_UNTRUSTED_HISTORY = "REJECTED_UNTRUSTED_HISTORY"
    REJECTED_FILTER_CONFLICT = "REJECTED_FILTER_CONFLICT"


class EstimatedCostClass(StrEnum):
    LOCAL = "LOCAL"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    EXPENSIVE = "EXPENSIVE"
